version: "3.9"

services:
  php82:
    image: php8.2-fpm-alpine
    container_name: php82
    hostname: php82
    user: 1000:1000
    networks:
      - server-network
    volumes:
      - /home/roman/projects:/projects

networks:
  server-network:
    external: true
