version: "3.9"

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    hostname: nginx
    networks:
      - server-network
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 9070:9070
    volumes:
      - ./config:/etc/nginx
      - /home/roman/projects:/projects

      - ./certs/certs:/etc/ssl/certs/selfsigned
      - ./certs/private:/etc/ssl/private/selfsigned

networks:
  server-network:
    external: true
