version: "3.9"

services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    networks:
      - server-network
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./dumps:/dumps

networks:
  server-network:
    external: true
